### ISSUE TITLE
Error: undefined is not an object evaluating 'react2.default.PropTypes.string'

### ISSUE THREAD

**Issue by Donhv** [melihmucuk/react-native-flat-button#4]
Pls check the lib.
When i try run example is meet error

**Comment by herarya** [comment]
@Donhv yes, problem PropTypes not update,
try this
`"react-native-flat-button": "github:herarya/react-native-flat-button"`

**Comment by melihmucuk** [comment]
fixed in v1.0.6 @Donhv @herarya
